# ============================================
# SymmetricDS Node Configuration - AMERICA (ROOT)
# ============================================

engine.name=america
group.id=america-store
external.id=001

# --------------------------------------------
# PostgreSQL connection
# --------------------------------------------
db.driver=org.postgresql.Driver
db.url=jdbc:postgresql://postgres-america:5432/globalshop
db.user=symmetricds
db.password=symmetricds

# --------------------------------------------
# ROOT NODE CONFIG
# --------------------------------------------
registration.url=
registration.open=true
auto.registration=true

# --------------------------------------------
# Sync URL
# --------------------------------------------
sync.url=http://symmetricds-america:31415/sync/america

# --------------------------------------------
# Jobs
# --------------------------------------------
job.push.period.time.ms=5000
job.pull.period.time.ms=5000
job.routing.period.time.ms=5000

start.push.job=true
start.pull.job=true
start.route.job=true
start.heartbeat.job=true
start.purge.job=true
start.synctriggers.job=true

# --------------------------------------------
# Auto Config
# --------------------------------------------
auto.reload=true
auto.upgrade=true
initial.load.create.first=true

# --------------------------------------------
# HTTP Server
# --------------------------------------------
http.enable=true
http.port=31415
http.timeout.ms=90000

# --------------------------------------------
# Logging
# --------------------------------------------
console.log.level=INFO
