engine.name=america
external.id=america
node.id=america
group.id=corp
db.driver=org.postgresql.Driver
db.url=jdbc:postgresql://postgres-america:5432/globalshop
db.user=symmetricds
db.password=symmetricds
registration.url=
auto.registration=true
http.port=31415