# Identificación del nodo
engine.name=europe
group.id=europe-store
external.id=002

# Conexión a MySQL
db.driver=com.mysql.cj.jdbc.Driver
db.url=jdbc:mysql://mysql-europe:3306/globalshop?allowPublicKeyRetrieval=true&useSSL=false
db.user=symmetricds
db.password=symmetricds

# REGISTRARSE contra el nodo América
registration.url=http://symmetricds-america:31415/sync/america

# Configuración de servicios
sync.url=http://symmetricds-europe:31416/sync/europe
http.enable=true
http.port=31416

# Habilitar jobs
start.push.job=true
start.pull.job=true
start.route.job=true
start.heartbeat.job=true

# Auto configuración
auto.register=true
auto.reload=true