engine.name=europe
external.id=europe
node.id=europe
group.id=store
db.driver=com.mysql.cj.jdbc.Driver
db.url=jdbc:mysql://mysql-europe:3306/globalshop
db.user=symmetricds
db.password=symmetricds
registration.url=http://symmetricds-america:31415/sync/america
http.port=31416