# ============================================
# SymmetricDS Server Configuration - EUROPA
# Puerto del servidor HTTP para el nodo Europa
# ============================================

# Hostname/IP address to bind
host.bind.name=0.0.0.0

# Enable HTTP synchronization
http.enable=true

# Port for HTTP (DIFERENTE al nodo América)
http.port=31416

# HTTPS disabled
https.enable=false
https2.enable=false
https.port=31417

# SSL settings
https.allow.self.signed.certs=true
https.verified.server.names=all
https.need.client.auth=false
https.want.client.auth=false

# Cookie settings
server.http.cookies.enabled=true
